apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: klw6wvocx-python 
  janus-idp.io/tekton: klw6wvocx-python
  backstage.io/kubernetes-id: klw6wvocx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: klw6wvocx-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  